<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.niuguwang.test.apitestJava.cases.LoginTest" tests="7" time="4.970" ignored="0" failures="1" timestamp="24 七月 2018 07:37:10 GMT" skipped="0" hostname="ngw9-PC" errors="0">
  <testcase name="loginTrue" time="4.321" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
  <testcase name="loginFalse01" time="0.095" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
  <testcase name="loginFalse03" time="0.070" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
  <testcase name="loginFalse" time="0.065" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
  <testcase name="loginFalse02" time="0.082" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
  <testcase name="loginFalse04" time="0.238" classname="com.niuguwang.test.apitestJava.cases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [用户名或密码错误] but found [参数错误]">
      <![CDATA[java.lang.AssertionError: expected [用户名或密码错误] but found [参数错误]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.niuguwang.test.apitestJava.cases.LoginTest.loginFalse04(LoginTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginFalse04 -->
  <testcase name="loginTrue01" time="0.099" classname="com.niuguwang.test.apitestJava.cases.LoginTest"/>
</testsuite> <!-- com.niuguwang.test.apitestJava.cases.LoginTest -->
